### ISSUE TITLE
After run $lite-server at the end of chapter 1

### ISSUE THREAD

**Issue by oim5nu** [oim5nu/learning-angular2#2]
Failed to load resource: the server responded with a status of 404 (Not Found)
zone.js:420 Unhandled Promise rejection: (SystemJS) XHR error (404 Not Found) loading http://localhost:3000/traceur
	Error: XHR error (404 Not Found) loading http://localhost:3000/traceur
	    at XMLHttpRequest.wrapFn [as _onreadystatechange] (http://localhost:3000/node_modules/zone.js/dist/zone.js:1039:29) [<root>]
	    at Zone.runTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:151:47) [<root> => <root>]
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:345:33) [<root>]
	Error loading http://localhost:3000/traceur
	Unable to load transpiler to transpile http://localhost:3000/node_modules/@angular/core/index.js
	Error loading http://localhost:3000/node_modules/@angular/core/index.js as "@angular/core" from http://localhost:3000/built/hello-angular.js ; Zone: <root> ; Task: Promise.then ; Value: ZoneAwareError (SystemJS) XHR error (404 Not Found) loading http://localhost:3000/traceur
	Error: XHR error (404 Not Found) loading http://localhost:3000/traceur
	    at XMLHttpRequest.wrapFn [as _onreadystatechange] (http://localhost:3000/node_modules/zone.js/dist/zone.js:1039:29) [<root>]
	    at Zone.runTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:151:47) [<root> => <root>]
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:345:33) [<root>]
	Error loading http://localhost:3000/traceur
	Unable to load transpiler to transpile http://localhost:3000/node_modules/@angular/core/index.js
	Error loading http://localhost:3000/node_modules/@angular/core/index.js as "@angular/core" from http://localhost:3000/built/hello-angular.js
consoleError @ zone.js:420
zone.js:422 ZoneAwareError

**Comment by oim5nu** [comment]
"The reason behind is that loading the umd modules from the bundle folders does not trigger the traceur transpiler as it assumes the library module is already in the correct format. Otherwise, it may assume that the code is written in es2015 and it needs transpilation so it invokes traceur."

http://stackoverflow.com/questions/37022526/angular-2-404-traceur-not-found/39945348#39945348
Replicate systemjs.config.js from https://github.com/angular/quickstart/blob/master/systemjs.config.js, and issue solved.
